# Generated by Django 3.2.7 on 2021-09-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210919_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(default=52),
            preserve_default=False,
        ),
    ]
